### ISSUE TITLE
Update deconLNR to be compatible with logNormReg v0.4.0

### ISSUE THREAD

**Issue by maddygriz** [Nanostring-Biostats/SpatialDecon#21]
logNormReg was updated to v0.4.0 10/12/2021 and breaks our unit tests. 
SpatialDecon version v1.3 requires logNormReg <= v0.3. 

Here is the NEWS update from logNormReg. The most likely updates that change our calculation are bolded.  
### version 0.4.0
* **lognlm(.., lik=FALSE) accepts argument 'weights' (thanks to Vito Ilacqua (Env Prot Ag) for his input). 'lik=FALSE' is the default now.**
* changes in vcov.lognlm: argument 'sandw' removed (it is always TRUE) and new argument 'exH' added.
* **if lik=FALSE the dispersion parameter is estimated taking n-p rather then n in the denominator.**
* type='gradient' in confint.lognlm() is allowed even for non-likelihood fits obtained via lik=FALSE.
* extractAIC() optionally can return the BIC (by setting k<=0).

**Comment by NicoleEO** [comment]
@maddygriz can you add a note in the News file re: future updates?

**Comment by maddygriz** [comment]
package was updated to 0.5.0 (2021-11-08)

* summary and print.summary return the (pseudo) R2 based on the log values
* two datasets (palermo and paris) included

DSPDA has updated version of logNormReg causing differences between package and plugin results.

**Comment by maddygriz** [comment]
Fixed in v1.7.3
