### ISSUE TITLE
CIBERSORT LM22 signature

### ISSUE THREAD

**Issue by yeswzc** [Nanostring-Biostats/SpatialDecon#26]
Can I use SpatialDecon and LM22 signature from CIBERSORT to deconvolve nanostring CTA profiles?

Thanks

**Comment by maddygriz** [comment]
As long as the signature is a matrix with cell types as columns and genes as rows, SpatialDecon can use it as a profile matrix. 

||CellType1|CellType2|...|
|-|---------|-----------|--|
|GeneA|###|###||
|GeneB|###|###||
|...||||

I would also look into the gene overlap between the LM22 signature and the CTA panel. We don't have a guideline on exactly how much overlap there should be, but a higher gene list concordance will improve the accuracy of the deconvolution.

**Comment by patrickjdanaher** [comment]
Hi there - 
Three considerations for using the LM22 matrix:
1. SpatialDecon expects linear-scale cell profile matrices, so don't log-transform. 
2. I'm not sure whether you want to scale the matrix beforehand. Ideally the total counts in each column of the cell profile matrix reflect the total RNA within a cell type. Depending on how LM22 is set up, normalization could help or hurt. (But either way, it won't be a huge impact.)
3. If you're using cancer samples, you should consider removing genes that we've estimated to be highly expressed by cancer cells. See supplemental table 2 from the SpatialDecon manuscript for this info, or just take the intersection of the LM22 list with the rownames of SpatialDecon::SafeTME

**Comment by yeswzc** [comment]
Thank you! Sounds reasonable.
