### ISSUE TITLE
Which count matrix to use for creating custom cell profile matrix?

### ISSUE THREAD

**Issue by aelhossiny** [Nanostring-Biostats/SpatialDecon#32]
Hi, Thank you for such a wonderful tool. I am trying to create custom cell profile matrix from paired SC samples, yet I am quite confused which count matrix should I use. The options are

Using "raw" counts while setting the argument "normalize = TRUE"
Using RNA@data which are the normalized data
Using "integrated" count matrix, which is the batch corrected integrated count matrix

All of them give me different results, and for biological interpretation, they all seem valid (i.e. despite there is enrichment of another cell cluster, this cluster belongs to the same cell type)

Another question, which normalized GeoMx count matrix should I be using? I tried using the log_normalized count matrix and it doesn't work well as using the Q3_normalized count matrix that hasn't been log normalized yet.

I would really appreciate your help! Thank you!

**Comment by maddygriz** [comment]
Hi @aelhossiny,

We have not tested the best normalization method for the single-cell data in profile matrix generation, but I think it is safe to say that whatever method is best for the standalone single-cell data is best for creating a profile matrix. In your case, I would assume it is the batch corrected integrated count matrix. 

As for the normalization method on the GeoMx side, SpatialDecon expects linear-scale cell profile matrices so don't use log normalization.

Maddy

**Comment by aelhossiny** [comment]
just a follow up, I noted from the paper that described the algorithm that when optimizing 


Let Xp∙K be the cell proﬁle matrix giving the linear-scale expression of p genes over K cell types.

**Comment by aelhossiny** [comment]
just a follow up, I noted from the paper that described the algorithm that when optimizing 

β.1 = argminβ.i||log(Y.i)−log(B.i+Xβ.i)||
Xp∙K is defined as the cell proﬁle matrix giving the linear-scale expression of p genes over K cell types.

But the scRNASeq data is log normalized already? Does that mean I raw counts?

**Comment by maddygriz** [comment]
If you log normalized your scRNAseq data, then yes you should use the raw counts and normalize in SpatialDecon using the argument "normalize = TRUE". But if you normalized the scRNAseq data not using log normalization I would use that.
