### ISSUE TITLE
Enquiry about loading "nsclc" dataset

### ISSUE THREAD

**Issue by jd10020** [Nanostring-Biostats/SpatialDecon#45]
Hi,

I just installed SpatialDecon and was following the vignette for the nsclc dataset. however when I run it I get the following error:
nsclc
NanoStringGeoMxSet (storageMode: lockedEnvironment)
assayData: 1700 features, 199 samples 
  element names: exprs, exprs_norm 
protocolData
  sampleNames: ROI01Tumor ROI01TME ... ROI100TME (199 total)
  varLabels: Mask.type RawReads ... NormFactorHK (18 total)
  varMetadata: labelDescription
phenoData
  sampleNames: ROI01Tumor ROI01TME ... ROI100TME (199 total)
  varLabels: Sample_ID Tissue ... istumor (10 total)
  varMetadata: labelDescription
featureData
  featureNames: ABCF1 ABL1 ... LAG3 (1700 total)
  fvarLabels: TargetName HUGOSymbol ... Negative (9 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation: kiloplex with cell type spike-in [legacy panel] 
signature: none
feature: Probe
analyte: Error in analyte(object) : 
  no slot of name "analyte" for this object of class "NanoStringGeoMxSet"
Error during wrapup: no slot of name "analyte" for this object of class "NanoStringGeoMxSet"
Error: no more error handlers available (recursive errors?); invoking 'abort' restart

and it tells me the feature is probe instead of target and there is no slot name for "analyte".

Does anyone know why this is happening? or do I need to install/ update any additional package?

Thanks

**Comment by jd10020** [comment]
Hi, I ran that code and it uploaded it. however the object has no "target" feature only the "probe" one. How can I change it to "target" for coercion into Seurat?

Thanks,
Juan-Diego

**Comment by maddygriz** [comment]
Hi Juan-Diego, 

I'm not sure I understand your question. The NSCLC GeoMxSet object from the vignette is on the "target" level. 
![image](https://user-images.githubusercontent.com/40255151/215818209-bbebe73d-8ca7-4bd4-908e-c84c10e80241.png)

If you are working with your own data that uses the CTA panel, you can use the function `GeomxTools::aggregateCounts()` to change from "probe" level to "target" level. 

Maddy

**Comment by jd10020** [comment]
Hi Maddy,
Thanks for your response. The object from the vignette I have is on "probe" level and apparently it does not include the "target" level. I used the aggregateCounts to change but did not work.
<img width="687" alt="Screenshot 2023-01-31 at 12 18 25 PM" src="https://user-images.githubusercontent.com/66746714/215835286-dc494045-9530-46d0-b8d1-fed41dc8b9f7.png">

Thanks,
Juan-Diego
