### ISSUE TITLE
Spatial decon visium issue

### ISSUE THREAD

**Issue by chrkuo** [Nanostring-Biostats/SpatialDecon#49]
I am utilizing spatialdecon to estimate the cell fractions of each spatial spot in my visium 10x tumor sample.

from reading your vignette there seems to be a few limitations with using visium data in spatialdecon.

I have encountered an error as I was trying to perform cell abundance estimates:

sharedgenes = intersect(rownames(raw), rownames(safeTME))
plot(colSums(raw), colSums(raw[sharedgenes, ]), log = "xy")

Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'plot': 'x' must be an array of at least two dimensions

I'm not sure how to get through this error and if it's just the nature of using visium data?

**Comment by maddygriz** [comment]
Hi @chrkuo,

Our support team will reach out to discuss further. Thank you for your understanding.

Maddy
