### ISSUE TITLE
Top genes driving deconvolution for each cell type? 

### ISSUE THREAD

**Issue by apredeus** [Nanostring-Biostats/SpatialDecon#54]
Dear SpatialDecon team, 

We're used the tool to map single cell data into several Nanostring spatial slides, and the results seem to make sense. However, the overlap between the probes in the Nanostring experiment and the markers in our single cell atlas is fairly limited. Thus, we wanted to somehow extract the genes "driving" the decision for each cell type - and perhaps remove some cell types from the results, if only few relevant genes are in fact detected. 

Is there any way to extract this information (the per-gene coefficients) from SpatialDecon model? 

Thank you in advance!

-- Alex

**Comment by maddygriz** [comment]
Hi @apredeus,

Our customer support team will be able to help you with this. Please email [support@nanostring.com](mailto:support@nanostring.com) with your issue.

Thanks,
Maddy

**Comment by apredeus** [comment]
Hi Maddy, 

Thank you, I will do that.
